version: '3.8'
services:
  database:
    container_name: ezoom-db
    image: mysql:8.0
    ports:
      - '33060:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ezoom
      MYSQL_ROOT_PASSWORD: ezoom
